name: CORS Proxy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install http-server
        echo "Dependencies installed"

    - name: Start http-server
      run: |
        npx http-server . -p 8080 --cors -c-1 --headers "Access-Control-Allow-Origin: *" &
        sleep 10  # Wait 10 seconds for the server to start
        echo "HTTP server started successfully"

    - name: Verify server is running
      run: |
        curl -I http://localhost:8080 || { echo "Failed to connect to server"; exit 1; }
        echo "Server verification completed"

    - name: Keep server running
      run: |
        while true; do
          curl -sSf http://localhost:8080 && echo "Status OK" || { echo "Server is down"; break; }
          sleep 60
        done
      continue-on-error: true

    - name: Stop http-server
      if: always()
      run: |
        pkill http-server || echo "No server to stop"
        echo "HTTP server stopped"
