name: CORS Proxy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      continue-on-error: true

    - name: Start proxy server
      run: npm start
      continue-on-error: true

    - name: Verify proxy server is running
      run: curl -I http://localhost:8080
      continue-on-error: true

    - name: Debug info
      run: |
        echo "Node.js version:"
        node -v
        echo "Installed npm packages:"
        npm list
        echo "Checking system status..."
        ps -aux
        netstat -tuln
      continue-on-error: true

    - name: Keep GitHub Action running
      run: |
        while true; do sleep 60; echo "Action is running..."; done
      continue-on-error: true
