name: CORS Proxy

on:
  workflow_dispatch: # Mahdollistaa manuaalisen käynnistyksen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install http-server
        echo "Dependencies installed"

    - name: Start http-server
      run: |
        nohup npx http-server . -p 8080 --cors --headers "Access-Control-Allow-Origin: *" --headers "Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept" --headers "Access-Control-Allow-Methods: GET, POST, OPTIONS" --headers "Access-Control-Allow-Credentials: true" > server.log 2>&1 &
        sleep 10  # Wait 10 seconds for the server to start
        echo "HTTP server started successfully"

    - name: Verify server is running
      run: |
        curl -I http://localhost:8080 || { echo "Failed to connect to server"; exit 1; }
        echo "Server verification completed"

    - name: Keep server running and verify periodically
      run: |
        for i in {1..6}; do
          echo "Check $i/6 - Verifying server status..."
          curl -sSf http://localhost:8080 && echo "Status OK" || { echo "Server is down"; break; }
          sleep 10
        done
      continue-on-error: true

    - name: Stop http-server
      if: always()
      run: |
        pkill node || echo "No server to stop"
        rm -f /tmp/stop-server
        echo "HTTP server stopped"
