name: Stop Server

on:
  workflow_dispatch:

jobs:
  stop-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send stop signal
      run: |
        touch /tmp/stop-server
        echo "Stop server signal sent"

    - name: Verify stop signal
      run: |
        if [ -f /tmp/stop-server ]; then
          echo "Stop signal file exists";
        else
          echo "Stop signal file does not exist";
          exit 1;
        fi

    - name: Stop http-server
      run: |
        pkill node || { echo "No server process found"; }
        echo "HTTP server process stopped"

    - name: Confirm server stopped
      run: |
        if pgrep node > /dev/null; then
          echo "Server is still running";
          exit 1;
        else
          echo "Server has successfully stopped";
        fi
