name: Stop Server

on:
  workflow_dispatch:

jobs:
  stop-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send stop signal
      run: |
        touch /tmp/stop-server
        echo "Stop server signal sent"
